# .github/workflows/build-linux.yml
name: reusable linux arm build

on:
  workflow_call:
    outputs:
      artifact_name:
        description: "the name of the linux artifact"
        value: ${{ jobs.build-linux-arm.outputs.artifact_name }}

jobs:
  build-linux-arm:
    runs-on: ubuntu-24.04-arm
    outputs:
      artifact_name: ${{ steps.upload.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: "Update Ubuntu package indexes"
        run: |-
          sudo apt-get update

      - name: "Install Linux dependencies"
        run: |-
          sudo apt-get install --yes \
            ca-certificates \
            libjpeg-dev \
            libpng-dev \
            libpng-dev \
            pipewire \
            libpipewire-0.3-0t64 \
            libpipewire-0.3-common \
            libpipewire-0.3-modules \
            libwayland-dev \
            wayland-protocols \
            libcairo2-dev \
            libdbus-1-dev \
            libayatana-appindicator3-dev \
            libgirepository-2.0-dev \
            gstreamer1.0-pipewire \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-base-apps \
            gstreamer1.0 \
            python3-gi \
            gobject-introspection \
            gir1.2-girepository-3.0 \
            gir1.2-ayatanaappindicator3-0.1 \
            gir1.2-gtk-3.0 \
            gir1.2-gio-2.0 \
            gir1.2-gobject-2.0 \
            patchelf \
            libgl1 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-shape0 \
            libxcb-randr0 \
            libxcb-shm0 \
            libxcb-xfixes0 \
            libxcb-cursor0 \
            xvfb

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: build with pyinstaller (linux)
        run: xvfb-run pyinstaller owocr_linux.spec

      - name: build linux archive
        run: |
          zip -r dist/owocr.linux.zip dist/owocr/

      - name: upload linux artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-arm
          path: dist/owocr.linux.zip
