# .github/workflows/build-linux.yml
name: reusable linux build

on:
  workflow_call:
    outputs:
      artifact_name:
        description: "the name of the linux artifact"
        value: ${{ jobs.build-linux.outputs.artifact_name }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.upload.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: "Update Ubuntu package indexes"
        run: |-
          sudo apt-get update

      - name: "Install Linux dependencies"
        run: |-
          sudo apt-get install --yes libwayland-dev wayland-protocols libcairo2-dev libdbus-1-dev libgirepository-2.0-dev

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip install pyinstaller

      - name: build with pyinstaller (linux)
        run: pyinstaller owocr_linux.spec

      - name: build linux archive
        run: |
          zip -r dist/owocr.linux.zip dist/owocr/

      - name: upload linux artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/owocr.linux.zip
