%YAML 1.1
---
  
name: "Build Linux binary"

"on":
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      runner:
        type: string
        required: true
      extras:
        type: string
        required: false
        default: &default_extras "[faster-png,easyocr,rapidocr,meikiocr,lens,gvision,azure]"
  
  workflow_dispatch:
    inputs:
      name:
        description: |-
          The name of the created artifact.
        type: string
        required: true
        default: "binary-linux-x64"
      runner:
        description: |-
          The runner to use for the job.
          Must run Ubuntu.
        type: string
        required: true
        default: "ubuntu-24.04"
      extras:
        description: |-
          The extras to include.
          This is added as suffix to `pip install .`.
          If specified, make sure to include square brackets.
        type: string
        required: true
        default: *default_extras

jobs:
  build:
    name: "Build Linux binary"

    runs-on: "${{ inputs.runner }}"
    
    steps:
      - 
        # https://github.com/actions/checkout/releases/tag/v6.0.1
        name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          submodules: recursive
      -
        name: "Update Ubuntu package indexes"
        run: |-
          sudo apt-get update
      -
        name: "Install Ubuntu dependencies"
        run: |-
          sudo apt-get install --yes libwayland-dev wayland-protocols libcairo2-dev libdbus-1-dev libgirepository-2.0-dev
      -
        # https://github.com/actions/setup-python/releases/tag/v6.2.0
        name: "Setup Python via actions/setup-python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          # Get the latest Python version allowed by the package
          python-version-file: .python-version
          check-latest: true
          # Make caching explicit
          cache: pip
      -
        name: "Setup Python dependencies"
        run: |-
          pip install --group="binary" .
      -
        name: "Build binary"
        run: |-
          pyinstaller ./owocr_linux.spec
      -
        name: "Create tarball"
        run: |-
          mv dist tar
          mkdir dist
          tar --verbose --create --gzip --file dist/owocr-${{ inputs.name }}.tgz --directory tar/ .
      - 
        # https://github.com/actions/upload-artifact/releases/tag/v6.0.0
        name: "Upload build artifacts"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: "${{ inputs.name }}"
          path: dist/
